stages:
  - build
  - push
    #  - deploy


build:
  stage: build
  only: 
    - master
  script:
    - docker build -t docker.gurzu.net/gurzu/overwatch:latest .

push:
  stage: push
  only:
    - master
  script:
    - docker push docker.gurzu.net/gurzu/overwatch:latest

