default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['POSTGRES_URL_DEVELOPMENT']%>

staging:
  <<: *default
  url: <%= ENV['POSTGRES_URL_STAGING']%>

test:
  <<: *default
  url: <%= ENV['POSTGRES_URL_TEST']%>
