Week.create!([
  {week: "2020-09-25 09:34:05 +0545"},
  {week: "2020-10-01 09:35:04 +0545"},
  {week: "2020-10-07 09:36:04 +0545"}
])

Project.create!([
  {project: "Spectrapass", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "MIlesone 3 Completed, New SOC in progress ", notes: "", week_id: 1},
  {project: "Almond", project_health: "Good", project_timeline: "On Halt", workload: "Relaxed", pending_raid: 1, milestone_status: "hold on milestone 2", notes: "*CMS complete", week_id: 1},
  {project: "Project Iron", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "Milesone 1 completed", notes: "", week_id: 1},
  {project: "ISM Publish", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "BoldCode", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "Flagship", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "Biggerpockets", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "Receptionist Server", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "Receptionist", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 1},
  {project: "Designerex", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: 1, milestone_status: "Task is on progress", notes: "", week_id: 1},
  {project: "ISM AD Tank", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "blocker state need credentials from client not yet received", week_id: 1},
  {project: "ISM SSP", project_health: "Good", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "since not negotiated so asked to hold the project\nhold from 6th october", week_id: 1},
  {project: "Overwatch", project_health: "Needs Checkup", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "Inhouse project", week_id: 1},
  {project: "Kryptonite", project_health: "Needs Checkup", project_timeline: "Due", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "", week_id: 1},
  {project: "Spectrapass", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "MIlesone 3 Completed, New SOC in progress ", notes: "", week_id: 2},
  {project: "Almond", project_health: "Good", project_timeline: "On Halt", workload: "Relaxed", pending_raid: 1, milestone_status: "hold on milestone 2", notes: "*CMS complete", week_id: 2},
  {project: "Project Iron", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "Milesone 1 completed", notes: "", week_id: 2},
  {project: "ISM Publish", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "BoldCode", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "Flagship", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "Biggerpockets", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "Receptionist Server", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "Receptionist", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 2},
  {project: "Designerex", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: 1, milestone_status: "Task is on progress", notes: "", week_id: 2},
  {project: "ISM AD Tank", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "blocker state need credentials from client not yet received", week_id: 2},
  {project: "ISM SSP", project_health: "Good", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "since not negotiated so asked to hold the project\nhold from 6th october", week_id: 2},
  {project: "Overwatch", project_health: "Needs Checkup", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "Inhouse project", week_id: 2},
  {project: "Kryptonite", project_health: "Needs Checkup", project_timeline: "Due", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "", week_id: 2},
  {project: "Spectrapass", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "MIlesone 3 Completed, New SOC in progress ", notes: "", week_id: 3},
  {project: "Almond", project_health: "Good", project_timeline: "On Halt", workload: "Relaxed", pending_raid: 1, milestone_status: "hold on milestone 2", notes: "*CMS complete", week_id: 3},
  {project: "Project Iron", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "Milesone 1 completed", notes: "", week_id: 3},
  {project: "ISM Publish", project_health: "Good", project_timeline: "On track", workload: "Stretched", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "BoldCode", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "Flagship", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "Biggerpockets", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "Receptionist Server", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "Receptionist", project_health: "Good", project_timeline: "On track", workload: "Relaxed", pending_raid: nil, milestone_status: "N/A", notes: "", week_id: 3},
  {project: "Designerex", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: 1, milestone_status: "Task is on progress", notes: "", week_id: 3},
  {project: "ISM AD Tank", project_health: "Good", project_timeline: "On track", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "blocker state need credentials from client not yet received", week_id: 3},
  {project: "ISM SSP", project_health: "Good", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "Task is on progress", notes: "since not negotiated so asked to hold the project\nhold from 6th october", week_id: 3},
  {project: "Overwatch", project_health: "Needs Checkup", project_timeline: "On Halt", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "Inhouse project", week_id: 3},
  {project: "Kryptonite", project_health: "Needs Checkup", project_timeline: "Due", workload: "Normal", pending_raid: nil, milestone_status: "", notes: "", week_id: 3}
])
Resource.create!([
  {project: "Spectrapass", no_of_resources: "10", week_id: 1},
  {project: "Almond", no_of_resources: "6", week_id: 1},
  {project: "Project Iron", no_of_resources: "3", week_id: 1},
  {project: "ISM Publish", no_of_resources: "8", week_id: 1},
  {project: "BoldCode", no_of_resources: "1", week_id: 1},
  {project: "Flagship", no_of_resources: "2", week_id: 1},
  {project: "Biggerpockets", no_of_resources: "1", week_id: 1},
  {project: "Receptionist Server", no_of_resources: "1", week_id: 1},
  {project: "Receptionist", no_of_resources: "1", week_id: 1},
  {project: "Designerex", no_of_resources: "1", week_id: 1},
  {project: "Benched", no_of_resources: "5", week_id: 1},
  {project: "Spectrapass", no_of_resources: "10", week_id: 2},
  {project: "Almond", no_of_resources: "6", week_id: 2},
  {project: "Project Iron", no_of_resources: "3", week_id: 2},
  {project: "ISM Publish", no_of_resources: "8", week_id: 2},
  {project: "BoldCode", no_of_resources: "1", week_id: 2},
  {project: "Flagship", no_of_resources: "2", week_id: 2},
  {project: "Biggerpockets", no_of_resources: "1", week_id: 2},
  {project: "Receptionist Server", no_of_resources: "1", week_id: 2},
  {project: "Receptionist", no_of_resources: "1", week_id: 2},
  {project: "Designerex", no_of_resources: "1", week_id: 2},
  {project: "Benched", no_of_resources: "5", week_id: 2},
  {project: "Spectrapass", no_of_resources: "10", week_id: 3},
  {project: "Almond", no_of_resources: "6", week_id: 3},
  {project: "Project Iron", no_of_resources: "3", week_id: 3},
  {project: "ISM Publish", no_of_resources: "8", week_id: 3},
  {project: "BoldCode", no_of_resources: "1", week_id: 3},
  {project: "Flagship", no_of_resources: "2", week_id: 3},
  {project: "Biggerpockets", no_of_resources: "1", week_id: 3},
  {project: "Receptionist Server", no_of_resources: "1", week_id: 3},
  {project: "Receptionist", no_of_resources: "1", week_id: 3},
  {project: "Designerex", no_of_resources: "1", week_id: 3},
  {project: "Benched", no_of_resources: "5", week_id: 3}
])
Milestone.create!([
  {project: "Spectrapass", no_of_milestones: 5, missed_milestones: 3, completed_milestones: 1, week_id: 1},
  {project: "Almond", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 1, week_id: 1},
  {project: "Zapp", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 0, week_id: 1},
  {project: "Spectrapass", no_of_milestones: 5, missed_milestones: 3, completed_milestones: 1, week_id: 2},
  {project: "Almond", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 1, week_id: 2},
  {project: "Zapp", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 0, week_id: 2},
  {project: "Spectrapass", no_of_milestones: 5, missed_milestones: 3, completed_milestones: 1, week_id: 3},
  {project: "Almond", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 1, week_id: 3},
  {project: "Zapp", no_of_milestones: 3, missed_milestones: 1, completed_milestones: 0, week_id: 3}
])
